config/routes.rb
Rails.application.routes.draw do
  get 'general_shopping_list/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  root 'users#index'

  resources :recipes do
    resources :food_recipes, only: %i[new create]
  end

  resources :food_recipes
  resources :foods
  resources :users

  get 'public_recipes', to: 'public_recipe#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :food_recipes
  has_many :foods, through: :food_recipes
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @food_recipe = FoodRecipe.new(recipe: @recipe)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  def create
    @recipe = Recipe.new(recipe_params)
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
        format.js { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.public
      @recipe.update(public: false)
      flash[:notice] = 'You have update the recipe status to private'
    else
      @recipe.update(public: true)
      flash[:notice] = 'You have update the recipe status to public'
    end
    redirect_to recipes_path
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.food_recipes.destroy_all
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    recipe = params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
    recipe[:user_id] = current_user.id
    recipe
  end

  def food_recipe_params
    params.require(:food_recipe).permit(:food_id, :recipe_id, :quantity)
  end

  def public_recipes
    @recipes = Recipe.where(public: true).includes(:user, :foods)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class='recipe-name'>All Recipes</h1>


<div id="recipes">
  <% @recipes.each do |recipe| %>
    <div class="recipe-card">
      <div class="recipe-header">
        <h4 class='sub-title'><%= recipe.name %></h4>
        <%= button_to "Remove", recipe_path(recipe.id), method: :delete, class: 'red-btn' %>
      </div>
      <div class="recipe-content">
        <p class='recipe-desc'><%= recipe.description %></p>
        <%= link_to "Show this recipe", recipe, class: 'link'%>
      </div>
    </div>
  <% end %>
</div>


<div>
<%if user_signed_in?%>
<%= link_to "New recipe", new_recipe_path, class: "green-btn" %>
<%end%>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<section>
  <h2 class='recipe-name'><%= @recipe.name %></h2>

  <div class='recipe-main'>
    
    <div class='public-btn-div'>
      <p class='sub-title'>Preparation time : <%= @recipe.preparation_time %></p>
      <div class='public-btn-flex'>
        <p class='sub-title'>Public :</p>
  <%= button_to  recipe_path(@recipe.id), :method => :patch, class: "align-self-end" do %>
      <% if @recipe.public %>
        <i class="fa fa-solid fa-toggle-on" style="font-size:28px;color:green"></i>
      <% end %>
      <% if !@recipe.public %>
         <i class="fa fa-solid fa-toggle-off" style="font-size:28px;color:red;border:none"></i>
      <% end %>
    <% end %>
      </div>
    </div>
    <div>
    <p class='sub-title'>Cooking time : <%= @recipe.cooking_time %></p>
    </div>

    <div>
    <p class='sub-title'>Steps goes here ...</p>
    </div>

    <div class='bottom-butoons'>
    <%= link_to 'General Shopping list', general_shopping_list_index_path(@food_recipe.recipe.id), class: "shopping-link" %>
    <%= link_to 'Add ingredient', new_food_recipe_path(@food_recipe.recipe.id), class: "ingredient-link"%>
    </div>
  </div>
   <hr>
   <table class="recipe-table">
   <thead class="table-thead">
       <tr>
           <th class="table-heading" scope="col">Food</th>
           <th class="table-heading" scope="col">Quantity</th>
           <th class="table-heading" scope="col">Value</th>
           <th class="table-heading" scope="col">Actions</th>
       </tr>
   </thead>
   <tbody>

   <% @recipe.food_recipes.each do |food_recipe| %>
       <tr>
           <td><%= food_recipe.food.name %></td>
           <td><%= food_recipe.food.measurement_unit %></td>
           <td>$<%= food_recipe.food.price * food_recipe.quantity %></td>
           <td>
               <% if can? :destroy, @recipe %>
               <div class="table-btn-div">
                   <%= button_to "Remove", food_recipe, method: :delete, class: "remove-button" %>
                   <%= link_to "Edit", edit_food_recipe_path(food_recipe), class: "edit-link" %>
               </div>
               <% end %>
           </td>
       </tr>
   <% end %>
   </tbody>
</table>

</section>


<div class='bottom-links'>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: 'green-btn' %> |
  <%= button_to "Destroy this recipe", @recipe, method: :delete , class: 'red-btn'%>
</div>
<%= link_to "Back to recipes", recipes_path, class: 'back-link' %>