config/routes.rb
Rails.application.routes.draw do
  get 'general_shopping_list/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  root 'users#index'

  resources :recipes do
    resources :food_recipes, only: %i[new create]
  end

  resources :food_recipes
  resources :foods
  resources :users

  get 'public_recipes', to: 'public_recipe#index'
end

app/models/food_recipe.rb
class FoodRecipe < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/controllers/food_recipes_controller.rb
class FoodRecipesController < ApplicationController
  before_action :set_food_recipe, only: %i[show edit update destroy]

  # GET /food_recipes or /food_recipes.json
  def index
    @food_recipes = FoodRecipe.all
  end

  # GET /food_recipes/1 or /food_recipes/1.json
  def show
    @food_recipe = FoodRecipe.find(params[:id])
    @recipe = Recipe.find(@food_recipe.recipe_id)
  end

  # GET /food_recipes/new
  def new
    @food_recipe = FoodRecipe.new
    @recipe_id = params[:recipe_id]
  end

  # GET /food_recipes/1/edit
  def edit
    @recipe_id = params[:recipe_id]
  end

  # POST /food_recipes or /food_recipes.json
  def create
    @food_recipe = FoodRecipe.new(food_recipe_params)
    @recipe = Recipe.find(params[:food_recipe][:recipe_id]) # Find the associated recipe

    @food_recipe.recipe = @recipe

    respond_to do |format|
      if @food_recipe.save
        format.html { redirect_to food_recipe_url(@food_recipe), notice: 'Food recipe was successfully created.' }
        format.json { render :show, status: :created, location: @food_recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_recipes/1 or /food_recipes/1.json
  def update
    respond_to do |format|
      if @food_recipe.update(food_recipe_params)
        format.html { redirect_to food_recipe_url(@food_recipe), notice: 'Food recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_recipes/1 or /food_recipes/1.json
  def destroy
    @food_recipe.destroy

    respond_to do |format|
      format.html { redirect_to food_recipes_url, notice: 'Food recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food_recipe
    @food_recipe = FoodRecipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_recipe_params
    params.require(:food_recipe).permit(:quantity, :food_id, :recipe_id)
  end
end

app/helpers/food_recipes_helper.rb
module FoodRecipesHelper
end

app/views/food_recipes/_food_recipe.html.erb
<div id="<%= dom_id food_recipe %>">
  <p>
    <strong>Quantity:</strong>
    <%= food_recipe.quantity %>
  </p>

</div>

app/views/food_recipes/_form.html.erb
<%= form_with(model: @food_recipe) do |form| %>
  <% if @food_recipe.errors.any? %>
    <div  id="error_explanation">
      <h2><%= pluralize(@food_recipe.errors.count, "error") %> prohibited this food_recipe from being saved:</h2>

      <ul>
        <% @food_recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :food_id %>
  <%= form.collection_select :food_id, Food.all, :id, :name %>

  <%= form.label :recipe_id %>
  <%= form.collection_select :recipe_id, Recipe.all, :id, :name %>

  <%= form.label :quantity %>
  <%= form.number_field :quantity %>

  <%= form.submit %>
<% end %>

app/views/food_recipes/edit.html.erb
<h1>Editing food recipe</h1>

<%= render "form", food_recipe: @food_recipe %>

<br>

<div>
  <%= link_to "Show this food recipe", @food_recipe %> |
  <%= link_to "Back to food recipes", food_recipes_path %>
</div>

app/views/food_recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Food recipes</h1>

<div id="food_recipes">
  <% @food_recipes.each do |food_recipe| %>
    <%= render food_recipe %>
    <p>
      <%= link_to "Show this food recipe", food_recipe %>
    </p>
  <% end %>
</div>

<%= link_to "New food recipe", new_food_recipe_path %>

app/views/food_recipes/new.html.erb
<h1>New food recipe</h1>

<%= render "form", food_recipe: @food_recipe %>

<br>

<div>
  <%= link_to "Back to food recipes", food_recipes_path %>
</div>

app/views/food_recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food_recipe %>

<div>
  <%= link_to "Edit this food recipe", edit_food_recipe_path(@food_recipe) %> |
  <%= link_to "Back to food recipes", food_recipes_path %>

  <%= button_to "Destroy this food recipe", @food_recipe, method: :delete %>
</div>